export class AddFormBasicRequestModel {
  constructor(
    public profileId?: number,

    public dealId?: number,
    public openedDate?: string,
    public description?: string,
    public customerService?: string,
    public acceptedPaymentMethods?: string,
    public voivodeship?: string,
    public city?: string,
    public street?: string,
    public postCode?: string,
    public phone?: string,
    public websiteUrl?: string,
    public visitsUrl?: string,
    public mondayFrom?: string,
    public mondayTo?: string,
    public tuesdayFrom?: string,
    public tuesdayTo?: string,
    public wednesdayFrom?: string,
    public wednesdayTo?: string,
    public thursdayFrom?: string,
    public thursdayTo?: string,
    public fridayFrom?: string,
    public fridayTo?: string,
    public saturdayFrom?: string,
    public saturdayTo?: string,
    public sundayFrom?: string,
    public sundayTo?: string,
    public atr1?: boolean,
    public atr2?: boolean,
    public atr3?: boolean,
    public atr4?: boolean,
    public atr5?: boolean,
    public atr6?: boolean,
    public atr7?: boolean,
    public atr8?: boolean,
    public atr9?: boolean,
    public atr10?: boolean,
    public atr11?: boolean,
    public atr12?: boolean,
    public atr13?: boolean,
    public atr14?: boolean,
    public atr15?: boolean,
    public atr16?: boolean,
    public atr17?: boolean,

    // For response
    public profileName?: string,
    public creationDate?: Date
  ) {}
}
